---
language: ruby
bundler_args: --without development assets
env: RAILS_ENV=travis acres_site_name="3000 Acres (travis)" acres_host="http://localhost:8080/"
rvm:
  - 2.1.1
before_script:
  - psql -c 'create database acres_test;' -U postgres
script:
  - bundle exec rake db:migrate --trace
  - bundle exec rspec spec/
