# Add account credentials and API keys here.
# See http://railsapps.github.io/rails-environment-variables.html
# This file should be listed in .gitignore to keep your settings secret!
# Each entry sets a local environment variable and overrides ENV variables in the Unix shell.
# For example, setting:
# GMAIL_USERNAME: Your_Gmail_Username
# makes 'Your_Gmail_Username' available as ENV["GMAIL_USERNAME"]
# Add application configuration variables here, as shown below.

# Set the region that should be appended to all addresses you use.
# Eg. if you have "1 Smith St, Smithville" and you want the full
# address to be "1 Smith St, Smithville, Smithlandia" you'd set it to
# "Smithlandia".  This is appended to the full address when using the
# geocoding service.
ACRES_REGION: Victoria, Australia

ADMIN_NAME: 3000 Acres
ADMIN_EMAIL: admin@3000acres.org
ROLES: [admin, user]
MANDRILL_USERNAME: admin@3000acres.org
MANDRILL_APIKEY: your key here

# Mailchimp is used to subscribe people to the newsletter
# Fetch list IDs using Gibbon:
#   Gibbon::API.api_key = '...'
#   gb = Gibbon::API.new
#   puts gb.lists.list.to_yaml
MAILCHIMP_APIKEY: your key here
MAILCHIMP_NEWSLETTER_ID: list id here
