development:
  access_key_id: ""
  secret_access_key: ""
    
test:
  access_key_id: ""
  secret_access_key: ""
    
travis:
  access_key_id: ""
  secret_access_key: ""

staging:
  access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  secret_access_key: <%= ENV['AWS_SECRET_KEY_ID'] %>

production:
  access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  secret_access_key: <%= ENV['AWS_SECRET_KEY_ID'] %>
