development:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000

test: &test
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

travis:
  adapter: postgresql
  database: acres_test
  username: postgres

production:
  adapter: postgresql
  database: acres_prod
  pool: 5
  timeout: 5000
  username: acres
  host: localhost
  password: thisisnottherealpassword

staging:
  adapter: postgresql
  database: acres_prod
  pool: 5
  timeout: 5000
  username: acres
  host: localhost
  password: thisisnottherealpassword
